import type { FileRowData } from "./documentsTableTypes";

export const DOCUMENTS_FILE_ROWS: FileRowData[] = [
  {
    id: "1",
    selected: true,
    icon: "PDF",
    iconClassName: "border-red-100 bg-red-50 text-red-600",
    name: "Rapport moral 2024.pdf",
    tags: ["AG 2024", "Officiel"],
    type: "PDF",
    size: "1,2 Mo",
    author: { initial: "ML", name: "M. Lefebvre", color: "bg-[#9333EA]" },
    date: "12 avr. 2025",
    access: "Public",
    accessClassName: "text-[#16A34A]",
    status: "Validé",
    statusClassName: "bg-[#DCFCE7] text-[#15803D]",
    statusDotClassName: "bg-[#22C55E]",
    version: "v3",
    showActions: true,
  },
  {
    id: "2",
    icon: "PDF",
    iconClassName: "border-red-100 bg-red-50 text-red-600",
    name: "Statuts association 2024.pdf",
    tags: ["Statuts"],
    type: "PDF",
    size: "340 Ko",
    author: { initial: "TD", name: "T. Durand", color: "bg-[#EC4899]" },
    date: "5 jan. 2025",
    access: "Public",
    accessClassName: "text-[#16A34A]",
    status: "Validé",
    statusClassName: "bg-[#DCFCE7] text-[#15803D]",
    statusDotClassName: "bg-[#22C55E]",
    version: "v2",
  },
  {
    id: "3",
    icon: "XLS",
    iconClassName: "border-emerald-100 bg-emerald-50 text-emerald-700",
    name: "Bilan financier 2024.xlsx",
    tags: ["Finance", "AG 2024"],
    type: "XLSX",
    size: "88 Ko",
    author: { initial: "SM", name: "S. Martin", color: "bg-[#2563EB]" },
    date: "10 avr. 2025",
    access: "Bureau",
    accessClassName: "text-[#2563EB]",
    status: "En attente",
    statusClassName: "bg-[#FFEDD5] text-[#C2410C]",
    statusDotClassName: "bg-[#F97316]",
    version: "v1",
  },
  {
    id: "4",
    icon: "DOC",
    iconClassName: "border-blue-100 bg-blue-50 text-blue-700",
    name: "PV Assemblée Générale 2025.docx",
    tags: ["AG 2025"],
    type: "DOCX",
    size: "54 Ko",
    author: { initial: "ML", name: "M. Lefebvre", color: "bg-[#9333EA]" },
    date: "15 avr. 2025",
    access: "Public",
    accessClassName: "text-[#16A34A]",
    status: "Brouillon",
    statusClassName: "bg-[#F3F4F6] text-[#4B5563]",
    statusDotClassName: "bg-[#9CA3AF]",
    version: "v1",
  },
  {
    id: "5",
    icon: "PPT",
    iconClassName: "border-orange-100 bg-orange-50 text-orange-600",
    name: "Présentation bilan AG 2025.pptx",
    tags: ["AG 2025", "Présentiel"],
    type: "PPTX",
    size: "3,8 Mo",
    author: { initial: "TD", name: "T. Durand", color: "bg-[#EC4899]" },
    date: "14 avr. 2025",
    access: "Public",
    accessClassName: "text-[#16A34A]",
    status: "Validé",
    statusClassName: "bg-[#DCFCE7] text-[#15803D]",
    statusDotClassName: "bg-[#22C55E]",
    version: "v2",
  },
  {
    id: "6",
    icon: "PDF",
    iconClassName: "border-red-50 bg-red-50/80 text-red-300",
    name: "Règlement intérieur 2020.pdf",
    tags: ["Archivé"],
    type: "PDF",
    size: "150 Ko",
    author: { initial: "JB", name: "J. Blanc", color: "bg-[#34D399]" },
    date: "2 jan. 2021",
    access: "Public",
    accessClassName: "text-[#9CA3AF]",
    status: "Archivé",
    statusClassName: "bg-[#F9FAFB] text-[#6B7280]",
    statusDotClassName: "bg-[#D1D5DB]",
    version: "v1",
    dim: true,
  },
];
