import type { FormationArticle, FormationCategory, FormationStat } from "./formationsTypes";

export const FORMATION_STATS: FormationStat[] = [
  { id: "total", label: "Articles totaux", value: "73", icon: "laptop", accent: "blue" },
  { id: "pub", label: "Publiés", value: "61", icon: "check", accent: "green" },
  { id: "draft", label: "Brouillons", value: "12", icon: "circle", accent: "orange" },
  { id: "cat", label: "Catégories", value: "19", icon: "folder", accent: "purple" },
  { id: "views", label: "Vues ce mois", value: "2.4k", icon: "eye", accent: "blue" },
];

export const FORMATION_CATEGORIES: FormationCategory[] = [
  { id: "amiante", name: "Amiante", count: 8 },
  { id: "audits", name: "Audits", count: 5 },
  { id: "bim", name: "BIM", count: 4 },
  { id: "chantier", name: "Chantier", count: 11 },
  { id: "eau", name: "Eau", count: 3 },
  { id: "energie", name: "Énergie", count: 7 },
  { id: "toitures", name: "Toitures", count: 6 },
];

export const FORMATION_ARTICLES: FormationArticle[] = [
  {
    id: "1",
    categoryId: "amiante",
    categoryName: "Amiante",
    status: "published",
    level: "Intermédiaire",
    title: "Diagnostic amiante avant travaux : tout savoir",
    icon: "warning",
    iconWrapClass: "bg-amber-50",
    iconClass: "text-amber-600",
  },
  {
    id: "2",
    categoryId: "audits",
    categoryName: "Audits",
    status: "published",
    level: "Avancé",
    title: "Audit énergétique réglementaire : méthodologie 2025",
    icon: "chart",
    iconWrapClass: "bg-sky-50",
    iconClass: "text-sky-600",
  },
  {
    id: "3",
    categoryId: "toitures",
    categoryName: "Toitures",
    status: "draft",
    level: "Expert",
    title: "Étanchéité toiture-terrasse : points de vigilance",
    icon: "home",
    iconWrapClass: "bg-violet-50",
    iconClass: "text-violet-600",
  },
  {
    id: "4",
    categoryId: "eau",
    categoryName: "Eau",
    status: "published",
    level: "Débutant",
    title: "Réseaux EU-EV : repérage et entretien courant",
    icon: "droplets",
    iconWrapClass: "bg-cyan-50",
    iconClass: "text-cyan-600",
  },
  {
    id: "5",
    categoryId: "chantier",
    categoryName: "Chantier",
    status: "published",
    level: "Intermédiaire",
    title: "Coordination SPS sur chantier : rôle du coordinateur",
    icon: "building",
    iconWrapClass: "bg-slate-100",
    iconClass: "text-slate-600",
  },
  {
    id: "6",
    categoryId: "energie",
    categoryName: "Énergie",
    status: "draft",
    level: "Avancé",
    title: "RE2020 : calcul des déperditions pas à pas",
    icon: "flame",
    iconWrapClass: "bg-orange-50",
    iconClass: "text-orange-600",
  },
  {
    id: "7",
    categoryId: "bim",
    categoryName: "BIM",
    status: "archived",
    level: "Expert",
    title: "Maquette numérique : niveau de détail attendu",
    icon: "building",
    iconWrapClass: "bg-neutral-100",
    iconClass: "text-neutral-500",
  },
];
